FROM php:8.1-fpm

WORKDIR /var/www/html

RUN apt-get update && apt-get install -y \
    libicu-dev \
    libpq-dev \
    libpng-dev \
    libzip-dev \
    zip \
    unzip \
    && docker-php-ext-configure intl \
    && docker-php-ext-install -j$(nproc) pdo pdo_mysql pgsql intl gd zip \
    && pecl install xdebug \
    && docker-php-ext-enable xdebug

COPY . .

RUN mv .env.example .env
