version: "3"

services:
    app:
        build: .
        ports:
            - "9000:9000"
        volumes:
            - .:/var/www/html
        environment:
            - APP_NAME=Laravel
            - APP_ENV=local
            - APP_KEY=base64:zGVOp3CyEEB9yue/G9DIkHJhtQ2p0gVc8cuUKb5453E=
            - APP_DEBUG=true
            - APP_URL=http://localhost
            - PUSHER_APP_KEY=your_pusher_app_key
            - PUSHER_APP_SECRET=your_pusher_app_secret
            - PUSHER_APP_ID=your_pusher_app_id
            - MIX_PUSHER_APP_KEY="${PUSHER_APP_KEY}"
            - MIX_PUSHER_APP_CLUSTER="${PUSHER_APP_CLUSTER}"
            - DB_CONNECTION=mysql
            - DB_HOST=127.0.0.1
            - DB_PORT=3306
            - DB_DATABASE=gorpratama
            - DB_USERNAME=root
            - DB_PASSWORD=
            - BROADCAST_DRIVER=pusher
            - CACHE_DRIVER=file
            - SESSION_DRIVER=file
            - SESSION_LIFETIME=120
            - QUEUE_CONNECTION=sync

    db:
        image: mysql:8.0
        ports:
            - "3307:3306"
        environment:
            - MYSQL_DATABASE=gorpratama
            - MYSQL_ROOT_PASSWORD=
            - MYSQL_ALLOW_EMPTY_PASSWORD=yes

    web:
        image: nginx:alpine
        ports:
            - "8000:80"
        volumes:
            - .:/var/www/html
            - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
        depends_on:
            - app
