version: "3"

services:
    app:
        build: .
        ports:
            - "80:80"
        depends_on:
            - db

    db:
        image: mysql:5.7
        environment:
            MYSQL_DATABASE: railway
            MYSQL_USER: root
            MYSQL_PASSWORD: Cl0mKrcTylUsHSrt1YvT
        ports:
            - "5988:3306"
