version: "3"

services:
    app:
        build:
            context: .
            dockerfile: Dockerfile
        ports:
            - "80:80"
        depends_on:
            - db
        environment:
            DB_CONNECTION: mysql
            DB_HOST: db
            DB_PORT: 3306
            DB_DATABASE: railway
            DB_USERNAME: root
            DB_PASSWORD: Cl0mKrcTylUsHSrt1YvT

    db:
        image: mysql:8.0
        environment:
            MYSQL_DATABASE: railway
            MYSQL_USER: root
            MYSQL_PASSWORD: Cl0mKrcTylUsHSrt1YvT
            MYSQL_ROOT_PASSWORD: Cl0mKrcTylUsHSrt1YvT
        ports:
            - "3306:3306"
