version: "3"

services:
    app:
        build:
            context: .
            dockerfile: Dockerfile
        image: your-image-name
        container_name: your-container-name
        ports:
            - "8080:80"
        environment:
            - APP_ENV=production
            - APP_DEBUG=false
            - APP_URL=http://localhost:8080
            - DB_CONNECTION=mysql
            - DB_HOST=your-hostname
            - DB_PORT=your-port
            - DB_DATABASE=your-database-name
            - DB_USERNAME=your-database-username
            - DB_PASSWORD=your-database-password
        volumes:
            - .:/var/www/html
        networks:
            - app-network

networks:
    app-network:
        driver: bridge
