version: "2.17.2"

services:
    # Laravel service
    app:
        build:
            context: .
            dockerfile: Dockerfile
        image: laravel
        container_name: laravel
        restart: unless-stopped
        volumes:
            - .:/var/www/html
        ports:
            - "8000:8000"
        environment:
            - APP_NAME=Laravel
            - APP_ENV=local
            - APP_DEBUG=true
            - APP_URL=http://localhost:8000
            - DB_CONNECTION=mysql
            - DB_HOST=127.0.0.1
            - DB_PORT=3306
            - DB_DATABASE=gorpratama
            - DB_USERNAME=root
            - DB_PASSWORD=
