version: "1"
name: Laravel ReactJS Vite TailwindCSS

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: railwayapp/laravel
    env:
      APP_NAME: ${APP_NAME}
      APP_ENV: ${APP_ENV}
      APP_KEY: ${APP_KEY}
      APP_DEBUG: ${APP_DEBUG}
      APP_URL: ${APP_URL}
      DB_CONNECTION: mysql
      DB_HOST: ${DB_HOST}
      DB_PORT: ${DB_PORT}
      DB_DATABASE: ${DB_DATABASE}
      DB_USERNAME: ${DB_USERNAME}
      DB_PASSWORD: ${DB_PASSWORD}

  db:
    image: mysql:8.0
    env:
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_USER: ${DB_USERNAME}
      MYSQL_PASSWORD: ${DB_PASSWORD}

  # frontend:
  #   build:
  #     context: ./frontend
  #     dockerfile: Dockerfile
  #   image: railwayapp/reactjs-vite-tailwindcss
  #   env:
  #     NODE_ENV: ${NODE_ENV}
  #     VITE_APP_API_URL: ${VITE_APP_API_URL}

  web:
    image: railwayapp/nginx
    env:
      NGINX_WORKER_PROCESSES: auto
      NGINX_HTTP_PORT: ${PORT}
      NGINX_SERVER_NAME: "${RAILWAY_APP_HOSTNAME}.railway.app"
      NGINX_SERVER_ROOT: /var/www/html/public
    ports:
      - "${PORT}:${PORT}"
    depends_on:
      - app
      # - frontend

  worker:
    image: railwayapp/worker
    env:
      QUEUE_CONNECTION: database
      DB_HOST: ${DB_HOST}
      DB_PORT: ${DB_PORT}
      DB_DATABASE: ${DB_DATABASE}
      DB_USERNAME: ${DB_USERNAME}
      DB_PASSWORD: ${DB_PASSWORD}
    depends_on:
      - app
    command: php artisan queue:work --sleep=3 --tries=3
