name: gorpratama
services:
  app:
    image: gorpratama
    env:
      APP_KEY: base64:GfC2h6hBt3BOtKRaASdfSYxZbTTu7iRq5bFb2DDW0BA=
      APP_ENV: production
      APP_DEBUG: false
      DB_CONNECTION: mysql
      DB_HOST: containers-us-west-52.railway.app
      DB_PORT: 5988
      DB_DATABASE: railway
      DB_USERNAME: root
      DB_PASSWORD: Cl0mKrcTylUsHSrt1YvT
      CACHE_DRIVER: redis
      SESSION_DRIVER: redis
      REDIS_HOST: containers-us-west-52.railway.app
      REDIS_PASSWORD: my-redis-password
      QUEUE_CONNECTION: database
    build:
      context: .
      dockerfile: Dockerfile
    command: php artisan serve --host 0.0.0.0 --port $PORT
    ports:
      - 80:8080
    depends_on:
      - db
  db:
    image: mysql:8.0
    env:
      MYSQL_ROOT_PASSWORD: Cl0mKrcTylUsHSrt1YvT
      MYSQL_DATABASE: railway
    ports:
      - 5988:3306
